export type JobStatusType =
  | 'In preparation'
  | 'Requested'
  | 'In progress'
  | 'Overdue'
  | 'Delivered'
  | 'Approved'
  | 'Invoice created'
  | 'Invoice accepted'
  | 'Paid'
  | 'Without invoice'
  | 'Canceled'

export type ProJobStatusType =
  | 'Approved'
  | 'Invoiced'
  | 'Paid'
  | 'Unassigned'
  | 'Canceled'
  | 'Without invoice'
  | 'Requested from LPM'
  | 'Awaiting approval'
  | 'In progress'
  | 'Job overdue'
  | 'Delivered to LPM'
  | 'Declined'
