export enum ServiceType {
  'Translation' = 'Translation',
  'Quality Control' = 'Quality Control',
  'Proofreading' = 'Proofreading',
  'Desktop Publishing' = 'Desktop Publishing',
  'Machine Translation Post Editing' = 'Machine Translation Post Editing',
  'Transcription' = 'Transcription',
  'Recording' = 'Recording',
  'Lip-sync' = 'Lip-sync',
  'Voice-over' = 'Voice-over',
  'Audio description' = 'Audio description',
  'Pre-mix' = 'Pre-mix',
  'Post-mix' = 'Post-mix',
  'In-person' = 'In-person',
  'Online' = 'Online',
  'Phone' = 'Phone',
  'Rendering/TC editing/Engineering' = 'Rendering/TC editing/Engineering',
  'Consultation' = 'Consultation',
  'SDH/CC' = 'SDH/CC',
  'Template/PLDL' = 'Template/PLDL',
  'Supplemental/Marketing' = 'Supplemental/Marketing',
  'File Prep' = 'File Prep',
  'Video Editing' = 'Video Editing',
  'Copywriting' = 'Copywriting',
}
