export enum ServiceType {
  'Audio description' = 'Audio description',
  'Copywriting' = 'Copywriting',
  'DTP' = 'DTP',
  'DTP QC' = 'DTP QC',
  'DTP file prep' = 'DTP file prep',
  'Dubbing' = 'Dubbing',
  'Dubbing audio QC' = 'Dubbing audio QC',
  'Dubbing script QC' = 'Dubbing script QC',
  'Dubbing script translation' = 'Dubbing script translation',
  'Editing' = 'Editing',
  'File preparation' = 'File preparation',
  'Final check' = 'Final check',
  'In-person' = 'In-person',
  'Localization engineering' = 'Localization engineering',
  'Online' = 'Online',
  'Phone' = 'Phone',
  'Proofreading' = 'Proofreading',
  'QC review' = 'QC review',
  'Rendering/TC editing' = 'Rendering/TC editing',
  'Revision(Rework)' = 'Revision(Rework)',
  'Subtitle' = 'Subtitle',
  'TAE(Translator accept edits)' = 'TAE(Translator accept edits)',
  'Transcription' = 'Transcription',
  'Translation' = 'Translation',
  'Video editing' = 'Video editing',
}
