export enum PriceUnit {
  'CAT discount' = 'CAT discount',
  'Characters' = 'Characters',
  'Days' = 'Days',
  'Document' = 'Document',
  'Fixed rate' = 'Fixed rate',
  'Graphics' = 'Graphics',
  'Hours' = 'Hours',
  'Info' = 'Info',
  'Lines' = 'Lines',
  'Minimum price' = 'Minimum price',
  'Minutes' = 'Minutes',
  'Months' = 'Months',
  'Pages' = 'Pages',
  'Paragraphs' = 'Paragraphs',
  'Percent' = 'Percent',
  'Segment' = 'Segment',
  'Term' = 'Term',
  'Unit' = 'Unit',
  'Words' = 'Words',
  'Years' = 'Years',
}
