import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Box } from '@mui/material'
import Info from './info'
import { Toaster } from 'react-hot-toast'
import Toolbar from './toolbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Toaster />
        <Box sx={{ display: 'flex', width: '100%', background: '#F0F0F6' }}>
          <Info />
          <main style={{ width: '100%' }}>{children}</main>
          <Toolbar />
        </Box>
      </body>
    </html>
  )
}
