import { OnboardingListType } from 'src/types/onboarding/list'

export const rows = [
  {
    id: 1,
    avatar: '8.png',
    full_name: "Korrie O'Crevy",

    post: 'Nuclear Power Engineer',
    email: 'kocrevy0@thetimes.co.uk',
    city: 'Krasnosilka',
    start_date: '09/23/2016',
    salary: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2,
  },
  {
    id: 7,
    avatar: '',
    full_name: 'Eileen Diehn',
    post: 'Environmental Specialist',
    email: 'ediehn6@163.com',
    city: 'Lampuyang',
    start_date: '10/15/2017',
    salary: 18991.67,
    age: '59',
    experience: '9 Years',
    status: 3,
  },
  {
    id: 11,
    avatar: '',
    full_name: 'De Falloon',
    post: 'Sales Representative',
    email: 'dfalloona@ifeng.com',
    city: 'Colima',
    start_date: '06/12/2018',
    salary: 19252.12,
    age: '30',
    experience: '0 Year',
    status: 4,
  },
  {
    id: 3,
    avatar: '7.png',
    full_name: 'Stella Ganderton',
    post: 'Operator',
    email: 'sganderton2@tuttocitta.it',
    city: 'Golcowa',
    start_date: '03/24/2018',
    salary: 13076.28,
    age: '66',
    experience: '6 Years',
    status: 5,
  },
  {
    id: 5,
    avatar: '',
    full_name: 'Harmonia Nisius',
    post: 'Senior Cost Accountant',
    email: 'hnisius4@gnu.org',
    city: 'Lucan',
    start_date: '08/25/2017',
    salary: 10909.52,
    age: '33',
    experience: '3 Years',
    status: 2,
  },
  {
    id: 6,
    avatar: '',
    full_name: 'Genevra Honeywood',
    post: 'Geologist',
    email: 'ghoneywood5@narod.ru',
    city: 'Maofan',
    start_date: '06/01/2017',
    salary: 17803.8,
    age: '61',
    experience: '1 Year',
    status: 1,
  },
  {
    id: 4,
    avatar: '8.png',
    full_name: 'Dorolice Crossman',
    post: 'Cost Accountant',
    email: 'dcrossman3@google.co.jp',
    city: 'Paquera',
    start_date: '12/03/2017',
    salary: 12336.17,
    age: '22',
    experience: '2 Years',
    status: 2,
  },
  {
    id: 8,
    avatar: '7.png',
    full_name: 'Richardo Aldren',
    post: 'Senior Sales Associate',
    email: 'raldren7@mtv.com',
    city: 'Skoghall',
    start_date: '11/05/2016',
    salary: 19230.13,
    age: '55',
    experience: '5 Years',
    status: 3,
  },
  {
    id: 9,
    avatar: '2.png',
    full_name: 'Allyson Moakler',
    post: 'Safety Technician',
    email: 'amoakler8@shareasale.com',
    city: 'Mogilany',
    start_date: '12/29/2018',
    salary: 11677.32,
    age: '39',
    experience: '9 Years',
    status: 5,
  },
  {
    id: 10,
    avatar: '7.png',
    full_name: 'Merline Penhalewick',
    post: 'Junior Executive',
    email: 'mpenhalewick9@php.net',
    city: 'Kanuma',
    start_date: '04/19/2019',
    salary: 15939.52,
    age: '23',
    experience: '3 Years',
    status: 2,
  },

  {
    id: 12,
    avatar: '',
    full_name: 'Cyrus Gornal',
    post: 'Senior Sales Associate',
    email: 'cgornalb@fda.gov',
    city: 'Boro Utara',
    start_date: '12/09/2017',
    salary: 16745.47,
    age: '22',
    experience: '2 Years',
    status: 4,
  },
  {
    id: 13,
    avatar: '',
    full_name: 'Tallou Balf',
    post: 'Staff Accountant',
    email: 'tbalfc@sina.com.cn',
    city: 'Siliana',
    start_date: '01/21/2016',
    salary: 15488.53,
    age: '36',
    experience: '6 Years',
    status: 4,
  },
  {
    id: 14,
    avatar: '',
    full_name: 'Othilia Extill',
    post: 'Associate Professor',
    email: 'oextilld@theatlantic.com',
    city: 'Brzyska',
    start_date: '02/01/2016',
    salary: 18442.34,
    age: '43',
    experience: '3 Years',
    status: 2,
  },
  {
    id: 15,
    avatar: '',
    full_name: 'Wilmar Bourton',
    post: 'Administrative Assistant',
    email: 'wbourtone@sakura.ne.jp',
    city: 'Bích Động',
    start_date: '04/25/2018',
    salary: 13304.45,
    age: '19',
    experience: '9 Years',
    status: 5,
  },
  {
    id: 16,
    avatar: '4.png',
    full_name: 'Robinson Brazenor',
    post: 'General Manager',
    email: 'rbrazenorf@symantec.com',
    city: 'Gendiwu',
    start_date: '12/23/2017',
    salary: 11953.08,
    age: '66',
    experience: '6 Years',
    status: 5,
  },
  {
    id: 17,
    avatar: '',
    full_name: 'Nadia Bettenson',
    post: 'Environmental Tech',
    email: 'nbettensong@joomla.org',
    city: 'Chabařovice',
    start_date: '07/11/2018',
    salary: 20484.44,
    age: '64',
    experience: '4 Years',
    status: 1,
  },
  {
    id: 18,
    avatar: '',
    full_name: 'Titus Hayne',
    post: 'Web Designer',
    email: 'thayneh@kickstarter.com',
    city: 'Yangon',
    start_date: '05/25/2019',
    salary: 16871.48,
    age: '59',
    experience: '9 Years',
    status: 1,
  },
  {
    id: 19,
    avatar: '4.png',
    full_name: 'Roxie Huck',
    post: 'Administrative Assistant',
    email: 'rhucki@ed.gov',
    city: 'Polýkastro',
    start_date: '04/04/2019',
    salary: 19653.56,
    age: '41',
    experience: '1 Year',
    status: 4,
  },
  {
    id: 20,
    avatar: '7.png',
    full_name: 'Latashia Lewtey',
    post: 'Actuary',
    email: 'llewteyj@sun.com',
    city: 'Hougong',
    start_date: '08/03/2017',
    salary: 18303.87,
    age: '35',
    experience: '5 Years',
    status: 1,
  },
  {
    id: 21,
    avatar: '',
    full_name: 'Natalina Tyne',
    post: 'Software Engineer',
    email: 'ntynek@merriam-webster.com',
    city: 'Yanguan',
    start_date: '03/16/2019',
    salary: 15256.4,
    age: '30',
    experience: '0 Year',
    status: 2,
  },
  {
    id: 22,
    avatar: '',
    full_name: 'Faun Josefsen',
    post: 'Analog Circuit Design manager',
    email: 'fjosefsenl@samsung.com',
    city: 'Wengyang',
    start_date: '07/08/2017',
    salary: 11209.16,
    age: '40',
    experience: '0 Year',
    status: 3,
  },
  {
    id: 23,
    avatar: '7.png',
    full_name: 'Rosmunda Steed',
    post: 'Assistant Media Planner',
    email: 'rsteedm@xing.com',
    city: 'Manzanares',
    start_date: '12/23/2017',
    salary: 13778.34,
    age: '21',
    experience: '1 Year',
    status: 5,
  },
  {
    id: 24,
    avatar: '',
    full_name: 'Scott Jiran',
    post: 'Graphic Designer',
    email: 'sjirann@simplemachines.org',
    city: 'Pinglin',
    start_date: '05/26/2016',
    salary: 23081.71,
    age: '23',
    experience: '3 Years',
    status: 1,
  },
  {
    id: 25,
    avatar: '',
    full_name: 'Carmita Medling',
    post: 'Accountant',
    email: 'cmedlingo@hp.com',
    city: 'Bourges',
    start_date: '07/31/2019',
    salary: 13602.24,
    age: '47',
    experience: '7 Years',
    status: 3,
  },
  {
    id: 26,
    avatar: '2.png',
    full_name: 'Morgen Benes',
    post: 'Senior Sales Associate',
    email: 'mbenesp@ted.com',
    city: 'Cà Mau',
    start_date: '04/10/2016',
    salary: 16969.63,
    age: '42',
    experience: '2 Years',
    status: 4,
  },
  {
    id: 27,
    avatar: '',
    full_name: 'Onfroi Doughton',
    post: 'Civil Engineer',
    email: 'odoughtonq@aboutads.info',
    city: 'Utrecht (stad)',
    start_date: '09/29/2018',
    salary: 23796.62,
    age: '28',
    experience: '8 Years',
    status: 3,
  },
  {
    id: 28,
    avatar: '',
    full_name: 'Kliment McGinney',
    post: 'Chief Design Engineer',
    email: 'kmcginneyr@paginegialle.it',
    city: 'Xiaocheng',
    start_date: '07/09/2018',
    salary: 24027.81,
    age: '28',
    experience: '8 Years',
    status: 4,
  },
  {
    id: 29,
    avatar: '',
    full_name: 'Devin Bridgland',
    post: 'Tax Accountant',
    email: 'dbridglands@odnoklassniki.ru',
    city: 'Baoli',
    start_date: '07/17/2016',
    salary: 13508.15,
    age: '48',
    experience: '8 Years',
    status: 3,
  },
  {
    id: 30,
    avatar: '6.png',
    full_name: 'Gilbert McFade',
    post: 'Biostatistician',
    email: 'gmcfadet@irs.gov',
    city: 'Deje',
    start_date: '08/28/2018',
    salary: 21632.3,
    age: '20',
    experience: '0 Year',
    status: 2,
  },
  {
    id: 31,
    avatar: '',
    full_name: 'Teressa Bleakman',
    post: 'Senior Editor',
    email: 'tbleakmanu@phpbb.com',
    city: 'Žebrák',
    start_date: '09/03/2016',
    salary: 24875.41,
    age: '37',
    experience: '7 Years',
    status: 5,
  },
  {
    id: 32,
    avatar: '',
    full_name: 'Marcelia Alleburton',
    post: 'Safety Technician',
    email: 'malleburtonv@amazon.com',
    city: 'Basail',
    start_date: '06/02/2016',
    salary: 23888.98,
    age: '53',
    experience: '3 Years',
    status: 2,
  },
  {
    id: 33,
    avatar: '7.png',
    full_name: 'Aili De Coursey',
    post: 'Environmental Specialist',
    email: 'adew@etsy.com',
    city: 'Łazy',
    start_date: '09/30/2016',
    salary: 14082.44,
    age: '27',
    experience: '7 Years',
    status: 5,
  },
  {
    id: 34,
    avatar: '6.png',
    full_name: 'Charlton Chatres',
    post: 'Analyst Programmer',
    email: 'cchatresx@goo.gl',
    city: 'Reguengos de Monsaraz',
    start_date: '04/07/2016',
    salary: 21386.52,
    age: '22',
    experience: '2 Years',
    status: 3,
  },
  {
    id: 35,
    avatar: '1.png',
    full_name: 'Nat Hugonnet',
    post: 'Financial Advisor',
    email: 'nhugonnety@wufoo.com',
    city: 'Pimentel',
    start_date: '09/11/2019',
    salary: 13835.97,
    age: '46',
    experience: '6 Years',
    status: 4,
  },
  {
    id: 36,
    avatar: '',
    full_name: 'Lorine Hearsum',
    post: 'Payment Adjustment Coordinator',
    email: 'lhearsumz@google.co.uk',
    city: 'Shuiying',
    start_date: '03/05/2019',
    salary: 22093.91,
    age: '47',
    experience: '7 Years',
    status: 4,
  },
  {
    id: 37,
    avatar: '5.png',
    full_name: 'Sheila-kathryn Haborn',
    post: 'Environmental Specialist',
    email: 'shaborn10@about.com',
    city: 'Lewolang',
    start_date: '11/10/2018',
    salary: 24624.23,
    age: '51',
    experience: '1 Year',
    status: 3,
  },
  {
    id: 38,
    avatar: '3.png',
    full_name: 'Alma Harvatt',
    post: 'Administrative Assistant',
    email: 'aharvatt11@addtoany.com',
    city: 'Ulundi',
    start_date: '11/04/2016',
    salary: 21782.82,
    age: '41',
    experience: '1 Year',
    status: 1,
  },
  {
    id: 39,
    avatar: '2.png',
    full_name: 'Beatrix Longland',
    post: 'VP Quality Control',
    email: 'blongland12@gizmodo.com',
    city: 'Damu',
    start_date: '07/18/2016',
    salary: 22794.6,
    age: '62',
    experience: '2 Years',
    status: 2,
  },
  {
    id: 40,
    avatar: '4.png',
    full_name: 'Hammad Condell',
    post: 'Project Manager',
    email: 'hcondell13@tiny.cc',
    city: 'Bulung’ur',
    start_date: '11/04/2018',
    salary: 10872.83,
    age: '37',
    experience: '7 Years',
    status: 4,
  },
  {
    id: 41,
    avatar: '',
    full_name: 'Parker Bice',
    post: 'Technical Writer',
    email: 'pbice14@ameblo.jp',
    city: 'Shanlian',
    start_date: '03/02/2016',
    salary: 17471.92,
    age: '65',
    experience: '5 Years',
    status: 5,
  },
  {
    id: 42,
    avatar: '',
    full_name: 'Lowrance Orsi',
    post: 'Biostatistician',
    email: 'lorsi15@wp.com',
    city: 'Dengteke',
    start_date: '12/10/2018',
    salary: 24719.51,
    age: '64',
    experience: '4 Years',
    status: 1,
  },
  {
    id: 43,
    avatar: '8.png',
    full_name: 'Ddene Chaplyn',
    post: 'Environmental Tech',
    email: 'dchaplyn16@nymag.com',
    city: 'Lattes',
    start_date: '01/23/2019',
    salary: 11958.33,
    age: '38',
    experience: '8 Years',
    status: 2,
  },
  {
    id: 44,
    avatar: '',
    full_name: 'Washington Bygraves',
    post: 'Human Resources Manager',
    email: 'wbygraves17@howstuffworks.com',
    city: 'Zlaté Hory',
    start_date: '09/07/2016',
    salary: 10552.43,
    age: '37',
    experience: '7 Years',
    status: 1,
  },
  {
    id: 45,
    avatar: '7.png',
    full_name: 'Meghann Bodechon',
    post: 'Operator',
    email: 'mbodechon18@1und1.de',
    city: 'Itō',
    start_date: '07/23/2018',
    salary: 23024.28,
    age: '61',
    experience: '1 Year',
    status: 4,
  },
  {
    id: 46,
    avatar: '1.png',
    full_name: 'Moshe De Ambrosis',
    post: 'Recruiting Manager',
    email: 'mde19@purevolume.com',
    city: 'San Diego',
    start_date: '02/10/2018',
    salary: 10409.9,
    age: '47',
    experience: '7 Years',
    status: 5,
  },
  {
    id: 47,
    avatar: '4.png',
    full_name: 'Had Chatelot',
    post: 'Cost Accountant',
    email: 'hchatelot1a@usatoday.com',
    city: 'Mercedes',
    start_date: '11/23/2016',
    salary: 11446.3,
    age: '64',
    experience: '4 Years',
    status: 4,
  },
  {
    id: 48,
    avatar: '',
    full_name: 'Georgia McCrum',
    post: 'Registered Nurse',
    email: 'gmccrum1b@icio.us',
    city: 'Nggalak',
    start_date: '04/19/2018',
    salary: 14002.31,
    age: '63',
    experience: '3 Years',
    status: 1,
  },
  {
    id: 49,
    avatar: '5.png',
    full_name: 'Krishnah Stilldale',
    post: 'VP Accounting',
    email: 'kstilldale1c@chronoengine.com',
    city: 'Slavs’ke',
    start_date: '03/18/2017',
    salary: 10704.29,
    age: '56',
    experience: '6 Years',
    status: 1,
  },
  {
    id: 50,
    avatar: '4.png',
    full_name: 'Mario Umbert',
    post: 'Research Assistant',
    email: 'mumbert1d@digg.com',
    city: 'Chorotis',
    start_date: '05/13/2019',
    salary: 21813.54,
    age: '43',
    experience: '3 Years',
    status: 1,
  },
  {
    id: 95,
    avatar: '2.png',
    full_name: 'Edwina Ebsworth',
    post: 'Human Resources Assistant',
    email: 'eebsworth2m@sbwire.com',
    city: 'Puzi',
    start_date: '09/27/2018',
    salary: 19586.23,
    age: '27',
    experience: '2 Years',
    status: 1,
  },
]

// export interface PersonalInfo {
//   firstName: string
//   middleName?: string
//   lastName: string
//   jobInfo: Array<JobInfoType>
//   experience: string
// }

export const rows2 = [
  {
    id: 'P-0010',
    userId: 2340938434,
    email: 'bon@glozinc.com',
    firstName: 'Kim',
    middleName: 'middle',
    lastName: 'bon',
    experience: '3-5years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Template author',
        source: 'KO',
        target: 'EN',
      },
      {
        jobType: 'Webcomics',
        role: 'Proofreader',
        source: 'KO',
        target: 'EN',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'P-0012',
    userId: 2340938434,
    email: 'bon@glozinc.com',
    firstName: 'Kim',
    middleName: 'middle',
    lastName: 'bon',
    experience: '3-5years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Template author',
        source: 'KO',
        target: 'EN',
      },
      {
        jobType: 'Webcomics',
        role: 'Proofreader',
        source: 'JA',
        target: 'EN',
      },
    ],
    testStatus: '',
    isOnboarded: false,
  },
]

export const clientGuide = [
  {
    id: 1,
    title: 'Naver webtoon guideline Ver.3',
    client: 'Naver',
    category: 'Webcomics',
    serviceType: ['Translation'],
    dueAt: 'Tue Jan 31 2023 00:40:09',
  },
  {
    id: 2,
    title: 'Tappytoon style guide',
    client: 'Tappytoon',
    category: 'Webnovel',
    serviceType: ['Translation', 'Proofreading', 'QC', 'DTP'],
    dueAt: 'Tue Jan 31 2023 00:40:09',
  },
  {
    id: 3,
    title: 'Naver webtoon guideline Ver.3',
    client: 'Naver',
    category: 'YouTube',
    serviceType: ['QC'],
    dueAt: 'Tue Jan 31 2023 00:40:09',
  },
  {
    id: 4,
    title: 'Naver webtoon guideline Ver.3',
    client: 'Naver',
    category: 'Webcomics',
    serviceType: ['Translation'],
    dueAt: 'Tue Jan 31 2023 00:40:09',
  },
]

export const onboardingData: OnboardingListType[] = [
  {
    id: 'BR-SP',
    userId: 1,
    email: 'kknock0@google.de',
    firstName: 'Henrietta',
    middleName: 'Karylin',
    lastName: 'Knock',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Editor',
        source: 'CN',
        target: 'SA',
      },
      {
        jobType: 'Misc.',
        role: 'Supp author',
        source: 'CO',
        target: 'BG',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'MM-17',
    userId: 2,
    email: 'mgerber1@unicef.org',
    firstName: 'Mersey',
    middleName: 'Marika',
    lastName: 'Gerber',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Translator',
        source: 'PH',
        target: 'ID',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'AR-W',
    userId: 3,
    email: 'bmccreagh2@unesco.org',
    firstName: 'Brew',
    middleName: null,
    lastName: 'McCreagh',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'DTPer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Dubbing',
        role: 'DTP QCer',
        source: 'CN',
        target: 'LK',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'US-FL',
    userId: 4,
    email: 'cruzek3@vistaprint.com',
    firstName: 'Pen',
    middleName: 'Chastity',
    lastName: 'Ruzek',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Interpreter',
        source: 'CN',
        target: 'RU',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'US-IL',
    userId: 5,
    email: 'efilkin4@squarespace.com',
    firstName: 'Oralie',
    middleName: 'Emelina',
    lastName: 'Filkin',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'SDH author',
        source: 'MA',
        target: 'ID',
      },
      {
        jobType: 'Webnovel',
        role: 'Webnovel translator',
        source: 'CO',
        target: 'CN',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'MR-01',
    userId: 6,
    email: 'cbeckey5@fc2.com',
    firstName: 'Carce',
    middleName: null,
    lastName: 'Beckey',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Template QCer',
        source: 'CZ',
        target: 'KZ',
      },
      {
        jobType: 'YouTube',
        role: 'Supp QCer',
        source: 'NO',
        target: 'US',
      },
      {
        jobType: 'YouTube',
        role: 'Wenovel QCer',
        source: 'CN',
        target: 'FR',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'AU-WA',
    userId: 7,
    email: 'btackett6@ihg.com',
    firstName: 'Barbaraanne',
    middleName: null,
    lastName: 'Tackett',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Dubbing script translator',
        source: 'AR',
        target: 'TH',
      },
      {
        jobType: 'Misc.',
        role: 'SDH author',
        source: 'UA',
        target: 'CZ',
      },
      {
        jobType: 'DTP',
        role: 'DTP QCer',
        source: 'CG',
        target: 'CN',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'ID-KS',
    userId: 8,
    email: 'amapholm7@vkontakte.ru',
    firstName: 'Elton',
    middleName: 'Abigale',
    lastName: 'Mapholm',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Template author',
        source: 'ID',
        target: 'PE',
      },
      {
        jobType: 'DTP',
        role: 'Subtitle author',
        source: 'CN',
        target: 'FI',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: true,
  },
  {
    id: 'US-GA',
    userId: 9,
    email: 'gfoskett8@dedecms.com',
    firstName: 'Saunders',
    middleName: 'Gwennie',
    lastName: 'Foskett',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Video editor',
        source: 'ID',
        target: 'UA',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Dubbing script translator',
        source: 'PK',
        target: 'CA',
      },
      {
        jobType: 'DTP',
        role: 'Template author',
        source: 'ID',
        target: 'PH',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: true,
  },
  {
    id: 'ZA-NW',
    userId: 10,
    email: 'rmaund9@cyberchimps.com',
    firstName: 'Mehetabel',
    middleName: 'Rachelle',
    lastName: 'Maund',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Template QCer',
        source: 'FR',
        target: 'BR',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'SDH author',
        source: 'NO',
        target: 'ID',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'TW-PEN',
    userId: 11,
    email: 'aandryunina@technorati.com',
    firstName: 'Annadiane',
    middleName: null,
    lastName: 'Andryunin',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Audio description QCer',
        source: 'RU',
        target: 'FO',
      },
      {
        jobType: 'Dubbing',
        role: 'Template author',
        source: 'CH',
        target: 'AR',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'US-UT',
    userId: 12,
    email: 'ajakubovskib@multiply.com',
    firstName: 'Farra',
    middleName: 'Arlene',
    lastName: 'Jakubovski',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Interpreter',
        source: 'FO',
        target: 'UA',
      },
      {
        jobType: 'Documents/Text',
        role: 'Subtitle author',
        source: 'CN',
        target: 'IE',
      },
      {
        jobType: 'Interpretation',
        role: 'SDH author',
        source: 'JP',
        target: 'US',
      },
      {
        jobType: 'Misc.',
        role: 'DTPer',
        source: 'CN',
        target: 'RU',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'UA-12',
    userId: 13,
    email: 'vemeryc@google.co.jp',
    firstName: 'Valerye',
    middleName: null,
    lastName: 'Emery',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Dubbing QCer',
        source: 'BA',
        target: 'CN',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: true,
  },
  {
    id: 'AU-QLD',
    userId: 14,
    email: 'kcammackd@examiner.com',
    firstName: 'Sergei',
    middleName: 'Kori',
    lastName: 'Cammack',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Dubbing QCer',
        source: 'PH',
        target: 'CN',
      },
      {
        jobType: 'Webnovel',
        role: 'Audio description QCer',
        source: 'RU',
        target: 'CN',
      },
      {
        jobType: 'Webcomics',
        role: 'Webnovel translator',
        source: 'HN',
        target: 'BR',
      },
      {
        jobType: 'Webnovel',
        role: 'Translator',
        source: 'BR',
        target: 'MN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'AR-R',
    userId: 15,
    email: 'sduffile@google.fr',
    firstName: 'Trent',
    middleName: 'Sharia',
    lastName: 'Duffil',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Interpreter',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'YouTube',
        role: 'Editor',
        source: 'BG',
        target: 'RU',
      },
      {
        jobType: 'Dubbing',
        role: 'QCer',
        source: 'GR',
        target: 'CN',
      },
      {
        jobType: 'Documents/Text',
        role: 'Video editor',
        source: 'CN',
        target: 'HN',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: true,
  },
  {
    id: 'RU-KHA',
    userId: 16,
    email: 'ewinridgef@netscape.com',
    firstName: 'Cristen',
    middleName: 'Estelle',
    lastName: 'Winridge',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Webnovel translator',
        source: 'PH',
        target: 'US',
      },
      {
        jobType: 'DTP',
        role: 'Template QCer',
        source: 'PT',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'US-CA',
    userId: 17,
    email: 'hblackledgeg@odnoklassniki.ru',
    firstName: 'Devland',
    middleName: 'Haily',
    lastName: 'Blackledge',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Translator',
        source: 'BR',
        target: 'CN',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'NO-05',
    userId: 18,
    email: 'rrobensh@51.la',
    firstName: 'Calla',
    middleName: 'Rosetta',
    lastName: 'Robens',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Dubbing script translator',
        source: 'CZ',
        target: 'PT',
      },
      {
        jobType: 'Misc.',
        role: 'Translator',
        source: 'GR',
        target: 'PK',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'FR-E',
    userId: 19,
    email: 'bpeytoni@meetup.com',
    firstName: 'Bernardine',
    middleName: 'Billie',
    lastName: 'Peyton',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'DTPer',
        source: 'PL',
        target: 'HT',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'US-GA',
    userId: 20,
    email: 'paiskovitchj@google.nl',
    firstName: 'Fayette',
    middleName: 'Pammie',
    lastName: 'Aiskovitch',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Dubbing script translator',
        source: 'BR',
        target: 'JP',
      },
      {
        jobType: 'Interpretation',
        role: 'Editor',
        source: 'RU',
        target: 'BR',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: true,
  },
  {
    id: 'US-NY',
    userId: 21,
    email: 'egonzalezk@goo.ne.jp',
    firstName: 'Padraic',
    middleName: 'Etty',
    lastName: 'Gonzalez',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Subtitle author',
        source: 'CN',
        target: 'LB',
      },
      {
        jobType: 'Misc.',
        role: 'Template author',
        source: 'RU',
        target: 'NL',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'CA-NU',
    userId: 22,
    email: 'mdurkerl@shareasale.com',
    firstName: 'Marchelle',
    middleName: null,
    lastName: 'Durker',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'SDH QCer',
        source: 'CN',
        target: 'PT',
      },
      {
        jobType: 'DTP',
        role: 'DTPer',
        source: 'ID',
        target: 'SE',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'US-AK',
    userId: 23,
    email: 'cbeavesm@blogtalkradio.com',
    firstName: 'Miranda',
    middleName: 'Cacilia',
    lastName: 'Beaves',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Translator',
        source: 'UA',
        target: 'CN',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: false,
  },
  {
    id: 'US-PA',
    userId: 24,
    email: 'ogirodiern@examiner.com',
    firstName: 'Osgood',
    middleName: null,
    lastName: 'Girodier',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Wenovel QCer',
        source: 'ID',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: false,
  },
  {
    id: 'US-IL',
    userId: 25,
    email: 'smacredmondo@sciencedaily.com',
    firstName: 'Kaine',
    middleName: 'Suzanne',
    lastName: 'MacRedmond',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Interpreter',
        source: 'VN',
        target: 'MA',
      },
      {
        jobType: 'Misc.',
        role: 'Webcomics translator',
        source: 'ID',
        target: 'UA',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'CN-51',
    userId: 26,
    email: 'eedgellerp@tinyurl.com',
    firstName: 'Eddy',
    middleName: 'Elisabeth',
    lastName: 'Edgeller',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Editor',
        source: 'SE',
        target: 'VC',
      },
      {
        jobType: 'Interpretation',
        role: 'SDH author',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Webcomics',
        role: 'Dubbing script translator',
        source: 'PH',
        target: 'TZ',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: true,
  },
  {
    id: 'PG-EHG',
    userId: 27,
    email: 'abillingslyq@drupal.org',
    firstName: 'Pamelina',
    middleName: 'Aleta',
    lastName: 'Billingsly',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Supp author',
        source: 'PH',
        target: 'ID',
      },
      {
        jobType: 'YouTube',
        role: 'Webnovel translator',
        source: 'CN',
        target: 'MT',
      },
      {
        jobType: 'Dubbing',
        role: 'DTP QCer',
        source: 'PT',
        target: 'CN',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'US-AZ',
    userId: 28,
    email: 'asturtr@weebly.com',
    firstName: 'Adlai',
    middleName: null,
    lastName: 'Sturt',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Webcomics translator',
        source: 'ID',
        target: 'PT',
      },
      {
        jobType: 'Webcomics',
        role: 'Supp author',
        source: 'RU',
        target: 'ID',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'US-AK',
    userId: 29,
    email: 'swarres@sfgate.com',
    firstName: 'Wilek',
    middleName: 'Sabra',
    lastName: 'Warre',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'Dubbing script translator',
        source: 'RU',
        target: 'JP',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: false,
  },
  {
    id: 'NC-U-A',
    userId: 30,
    email: 'schinnt@opera.com',
    firstName: 'Shauna',
    middleName: null,
    lastName: 'Chinn',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Subtitle author',
        source: 'PH',
        target: 'TN',
      },
      {
        jobType: 'Webcomics',
        role: 'Webcomics translator',
        source: 'AL',
        target: 'RS',
      },
      {
        jobType: 'Misc.',
        role: 'Wenovel QCer',
        source: 'NL',
        target: 'PE',
      },
      {
        jobType: 'Documents/Text',
        role: 'Interpreter',
        source: 'CZ',
        target: 'UA',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'US-NY',
    userId: 31,
    email: 'rmundallu@japanpost.jp',
    firstName: 'Irv',
    middleName: 'Rosabelle',
    lastName: 'Mundall',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Wenovel QCer',
        source: 'SS',
        target: 'BR',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: true,
  },
  {
    id: 'MX-OAX',
    userId: 32,
    email: 'csnapev@opensource.org',
    firstName: 'Carlota',
    middleName: null,
    lastName: 'Snape',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Webnovel translator',
        source: 'CN',
        target: 'UA',
      },
      {
        jobType: 'Interpretation',
        role: 'Proofreader',
        source: 'AR',
        target: 'MX',
      },
      {
        jobType: 'Misc.',
        role: 'Dubbing QCer',
        source: 'PT',
        target: 'CN',
      },
      {
        jobType: 'Webnovel',
        role: 'Webcomics QCer',
        source: 'CN',
        target: 'FR',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'NI-AN',
    userId: 33,
    email: 'rbegwellw@thetimes.co.uk',
    firstName: 'Lilah',
    middleName: 'Roda',
    lastName: 'Begwell',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Supp QCer',
        source: 'MK',
        target: 'NL',
      },
      {
        jobType: 'Documents/Text',
        role: 'Wenovel QCer',
        source: 'PT',
        target: 'ID',
      },
      {
        jobType: 'DTP',
        role: 'Subtitle author',
        source: 'KZ',
        target: 'ID',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'RU-MOS',
    userId: 34,
    email: 'hdebernardisx@cbc.ca',
    firstName: 'Heloise',
    middleName: null,
    lastName: 'De Bernardis',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Dubbing script translator',
        source: 'SE',
        target: 'CN',
      },
      {
        jobType: 'Interpretation',
        role: 'DTP QCer',
        source: 'CO',
        target: 'MK',
      },
      {
        jobType: 'Interpretation',
        role: 'Proofreader',
        source: 'SE',
        target: 'KZ',
      },
      {
        jobType: 'Webnovel',
        role: 'Template QCer',
        source: 'RU',
        target: 'UG',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'US-PA',
    userId: 35,
    email: 'jmcmanameny@altervista.org',
    firstName: 'Matthew',
    middleName: 'Joann',
    lastName: 'McManamen',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Video editor',
        source: 'CN',
        target: 'NZ',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'US-OH',
    userId: 36,
    email: 'esonierz@businesswire.com',
    firstName: 'Elysha',
    middleName: null,
    lastName: 'Sonier',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Template QCer',
        source: 'NZ',
        target: 'DO',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'UA-63',
    userId: 37,
    email: 'areaveley10@so-net.ne.jp',
    firstName: 'Anton',
    middleName: null,
    lastName: 'Reaveley',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'DTPer',
        source: 'CN',
        target: 'SE',
      },
      {
        jobType: 'Misc.',
        role: 'Proofreader',
        source: 'PT',
        target: 'NC',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'TL-DI',
    userId: 38,
    email: 'mphettis11@nih.gov',
    firstName: 'Niven',
    middleName: 'Melosa',
    lastName: 'Phettis',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Interpreter',
        source: 'BR',
        target: 'ER',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'DTPer',
        source: 'VE',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: false,
  },
  {
    id: 'VN-49',
    userId: 39,
    email: 'amcilwrick12@friendfeed.com',
    firstName: 'Lenora',
    middleName: 'Andromache',
    lastName: 'Mc Ilwrick',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Translator',
        source: 'CN',
        target: 'UA',
      },
      {
        jobType: 'Dubbing',
        role: 'Webcomics QCer',
        source: 'BR',
        target: 'FR',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: false,
  },
  {
    id: 'US-IA',
    userId: 40,
    email: 'douldcott13@telegraph.co.uk',
    firstName: 'Tyrone',
    middleName: 'Deloria',
    lastName: 'Ouldcott',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Interpreter',
        source: 'PH',
        target: 'BR',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Video editor',
        source: 'PH',
        target: 'SE',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Translator',
        source: 'US',
        target: 'PL',
      },
      {
        jobType: 'YouTube',
        role: 'Webcomics QCer',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'UY-PA',
    userId: 41,
    email: 'nvasilyonok14@whitehouse.gov',
    firstName: 'Petra',
    middleName: 'Netti',
    lastName: 'Vasilyonok',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Webnovel translator',
        source: 'SE',
        target: 'DE',
      },
      {
        jobType: 'Webcomics',
        role: 'Interpreter',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Misc.',
        role: 'Interpreter',
        source: 'RU',
        target: 'PE',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'US-AK',
    userId: 42,
    email: 'dygou15@smugmug.com',
    firstName: 'Lizzy',
    middleName: 'Daisi',
    lastName: 'Ygou',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'SDH QCer',
        source: 'BY',
        target: 'CN',
      },
      {
        jobType: 'DTP',
        role: 'Wenovel QCer',
        source: 'AM',
        target: 'GW',
      },
      {
        jobType: 'Misc.',
        role: 'Webcomics QCer',
        source: 'CN',
        target: 'ID',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: false,
  },
  {
    id: 'ES-CN',
    userId: 43,
    email: 'jembling16@washington.edu',
    firstName: 'Klarika',
    middleName: 'Joline',
    lastName: 'Embling',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Webcomics translator',
        source: 'SE',
        target: 'CI',
      },
      {
        jobType: 'Dubbing',
        role: 'DTPer',
        source: 'MG',
        target: 'CN',
      },
      {
        jobType: 'Documents/Text',
        role: 'Interpreter',
        source: 'ID',
        target: 'SE',
      },
      {
        jobType: 'Documents/Text',
        role: 'SDH author',
        source: 'RU',
        target: 'PH',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: false,
  },
  {
    id: 'GR-92',
    userId: 44,
    email: 'jknotte17@zdnet.com',
    firstName: 'Jamie',
    middleName: null,
    lastName: 'Knotte',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Translator',
        source: 'PH',
        target: 'CN',
      },
      {
        jobType: 'Webnovel',
        role: 'Template QCer',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: true,
  },
  {
    id: 'IN-CT',
    userId: 45,
    email: 'mmanning18@godaddy.com',
    firstName: 'Huberto',
    middleName: 'Michelle',
    lastName: 'Manning',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Subtitle author',
        source: 'HR',
        target: 'CI',
      },
      {
        jobType: 'Webnovel',
        role: 'DTP QCer',
        source: 'BR',
        target: 'CA',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: false,
  },
  {
    id: 'BR-RS',
    userId: 46,
    email: 'cbrower19@infoseek.co.jp',
    firstName: 'Cassey',
    middleName: 'Cal',
    lastName: 'Brower',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Proofreader',
        source: 'PH',
        target: 'BR',
      },
      {
        jobType: 'Documents/Text',
        role: 'Webcomics QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'YouTube',
        role: 'Dubbing script translator',
        source: 'CN',
        target: 'US',
      },
      {
        jobType: 'YouTube',
        role: 'Dubbing QCer',
        source: 'BR',
        target: 'CN',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: false,
  },
  {
    id: 'RU-KHM',
    userId: 47,
    email: 'bcoventry1a@businessweek.com',
    firstName: 'Tomaso',
    middleName: 'Benedetta',
    lastName: 'Coventry',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'Dubbing script translator',
        source: 'PT',
        target: 'BR',
      },
      {
        jobType: 'Webcomics',
        role: 'Supp author',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'PH-CAP',
    userId: 48,
    email: 'ewilshere1b@about.com',
    firstName: 'Ethelred',
    middleName: null,
    lastName: 'Wilshere',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Webcomics translator',
        source: 'RU',
        target: 'SY',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'BR-SC',
    userId: 49,
    email: 'blemanu1c@webeden.co.uk',
    firstName: 'Alvira',
    middleName: 'Bunny',
    lastName: 'Lemanu',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Subtitle QCer',
        source: 'PH',
        target: 'BJ',
      },
      {
        jobType: 'YouTube',
        role: 'Wenovel QCer',
        source: 'RU',
        target: 'CN',
      },
      {
        jobType: 'Webnovel',
        role: 'Template author',
        source: 'FI',
        target: 'ID',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: true,
  },
  {
    id: 'ZM-03',
    userId: 50,
    email: 'bterrell1d@delicious.com',
    firstName: 'Bessie',
    middleName: null,
    lastName: 'Terrell',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Proofreader',
        source: 'VN',
        target: 'BR',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: true,
  },
  {
    id: 'US-MT',
    userId: 51,
    email: 'sdressel1e@jiathis.com',
    firstName: 'Jesse',
    middleName: 'Shirleen',
    lastName: 'Dressel',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Template QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Webcomics',
        role: 'DTP QCer',
        source: 'LT',
        target: 'PE',
      },
      {
        jobType: 'DTP',
        role: 'Supp QCer',
        source: 'PK',
        target: 'CN',
      },
      {
        jobType: 'Documents/Text',
        role: 'Translator',
        source: 'RU',
        target: 'ID',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: false,
  },
  {
    id: 'US-SC',
    userId: 52,
    email: 'rphettis1f@mail.ru',
    firstName: 'Ricardo',
    middleName: 'Rhianna',
    lastName: 'Phettis',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'DTPer',
        source: 'DK',
        target: 'PE',
      },
      {
        jobType: 'Interpretation',
        role: 'SDH author',
        source: 'PL',
        target: 'PT',
      },
      {
        jobType: 'Interpretation',
        role: 'Wenovel QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Dubbing',
        role: 'Editor',
        source: 'FR',
        target: 'CN',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: true,
  },
  {
    id: 'ID-PA',
    userId: 53,
    email: 'fvasenin1g@moonfruit.com',
    firstName: 'Forest',
    middleName: null,
    lastName: 'Vasenin',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Editor',
        source: 'TH',
        target: 'CN',
      },
      {
        jobType: 'Dubbing',
        role: 'DTP QCer',
        source: 'ID',
        target: 'BF',
      },
      {
        jobType: 'Interpretation',
        role: 'Editor',
        source: 'AZ',
        target: 'CO',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Dubbing QCer',
        source: 'PL',
        target: 'BR',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'AR-W',
    userId: 54,
    email: 'dgashion1h@typepad.com',
    firstName: 'Maryl',
    middleName: 'Dosi',
    lastName: 'Gashion',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Copywriter',
        source: 'RU',
        target: 'PL',
      },
      {
        jobType: 'Dubbing',
        role: 'SDH author',
        source: 'CZ',
        target: 'ID',
      },
      {
        jobType: 'Documents/Text',
        role: 'DTPer',
        source: 'BR',
        target: 'CN',
      },
      {
        jobType: 'YouTube',
        role: 'Interpreter',
        source: 'FI',
        target: 'MX',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: false,
  },
  {
    id: 'CA-BC',
    userId: 55,
    email: 'dplayer1i@google.ru',
    firstName: 'Drusy',
    middleName: 'Dani',
    lastName: 'Player',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Video editor',
        source: 'KI',
        target: 'BD',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: true,
  },
  {
    id: 'BR-RS',
    userId: 56,
    email: 'vbucham1j@seattletimes.com',
    firstName: 'Hollis',
    middleName: 'Vera',
    lastName: 'Bucham',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'DTP QCer',
        source: 'DK',
        target: 'MY',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'GB-SCT',
    userId: 57,
    email: 'kdonise1k@ucsd.edu',
    firstName: 'Kirby',
    middleName: null,
    lastName: "D'Onise",
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Translator',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: true,
  },
  {
    id: 'US-MI',
    userId: 58,
    email: 'aearingey1l@spotify.com',
    firstName: 'Keenan',
    middleName: 'Andromache',
    lastName: 'Earingey',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Translator',
        source: 'ID',
        target: 'ET',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'IN-AR',
    userId: 59,
    email: 'smaskrey1m@drupal.org',
    firstName: 'Wenona',
    middleName: 'Sheelagh',
    lastName: 'Maskrey',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Dubbing script translator',
        source: 'DO',
        target: 'PH',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'VC-U-A',
    userId: 60,
    email: 'bpatullo1n@51.la',
    firstName: 'Jenifer',
    middleName: 'Bari',
    lastName: 'Patullo',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Subtitle QCer',
        source: 'CN',
        target: 'PL',
      },
      {
        jobType: 'Misc.',
        role: 'SDH QCer',
        source: 'MY',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: false,
  },
  {
    id: 'BR-MS',
    userId: 61,
    email: 'ctatlow1o@indiatimes.com',
    firstName: 'Eustace',
    middleName: 'Cloe',
    lastName: 'Tatlow',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Dubbing QCer',
        source: 'YE',
        target: 'CN',
      },
      {
        jobType: 'Misc.',
        role: 'Interpreter',
        source: 'CN',
        target: 'ID',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: false,
  },
  {
    id: 'PF-U-A',
    userId: 62,
    email: 'ecasewell1p@samsung.com',
    firstName: 'Eveline',
    middleName: 'Elvera',
    lastName: 'Casewell',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Interpreter',
        source: 'PH',
        target: 'CO',
      },
      {
        jobType: 'Webnovel',
        role: 'Webcomics translator',
        source: 'IT',
        target: 'ID',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: false,
  },
  {
    id: 'CA-QC',
    userId: 63,
    email: 'etuison1q@nydailynews.com',
    firstName: 'Patrica',
    middleName: 'Ellyn',
    lastName: 'Tuison',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Audio description QCer',
        source: 'PH',
        target: 'FR',
      },
      {
        jobType: 'Interpretation',
        role: 'Editor',
        source: 'CN',
        target: 'US',
      },
      {
        jobType: 'Webnovel',
        role: 'Webnovel translator',
        source: 'CN',
        target: 'CZ',
      },
      {
        jobType: 'Webnovel',
        role: 'Dubbing script translator',
        source: 'CN',
        target: 'JP',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: false,
  },
  {
    id: 'GL-U-A',
    userId: 64,
    email: 'lmicka1r@ox.ac.uk',
    firstName: 'Elaina',
    middleName: 'Leonelle',
    lastName: 'Micka',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Translator',
        source: 'ZA',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: false,
  },
  {
    id: 'UY-AR',
    userId: 65,
    email: 'atongs1s@toplist.cz',
    firstName: 'Nerte',
    middleName: 'Allegra',
    lastName: 'Tongs',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Video editor',
        source: 'GH',
        target: 'TZ',
      },
      {
        jobType: 'Interpretation',
        role: 'Wenovel QCer',
        source: 'BR',
        target: 'BR',
      },
      {
        jobType: 'YouTube',
        role: 'Dubbing script translator',
        source: 'CO',
        target: 'RU',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'CK-U-A',
    userId: 66,
    email: 'vgheeorghie1t@msn.com',
    firstName: 'Nicholas',
    middleName: 'Verina',
    lastName: 'Gheeorghie',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Interpreter',
        source: 'SE',
        target: 'RU',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'QCer',
        source: 'BR',
        target: 'AF',
      },
      {
        jobType: 'YouTube',
        role: 'Wenovel QCer',
        source: 'EC',
        target: 'BR',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'TC-MC',
    userId: 67,
    email: 'jobeney1u@rediff.com',
    firstName: 'Marve',
    middleName: 'Juliann',
    lastName: 'Obeney',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Template QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Interpretation',
        role: 'Dubbing script translator',
        source: 'CN',
        target: 'GT',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Supp QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Interpreter',
        source: 'BR',
        target: 'RU',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: true,
  },
  {
    id: 'PF-U-A',
    userId: 68,
    email: 'acorker1v@go.com',
    firstName: 'Graham',
    middleName: 'Agnes',
    lastName: 'Corker',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Template QCer',
        source: 'IR',
        target: 'RU',
      },
      {
        jobType: 'Dubbing',
        role: 'Supp QCer',
        source: 'ID',
        target: 'YE',
      },
      {
        jobType: 'Documents/Text',
        role: 'SDH QCer',
        source: 'PL',
        target: 'PY',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'PG-WPD',
    userId: 69,
    email: 'rbeard1w@nba.com',
    firstName: 'Bette-ann',
    middleName: 'Randee',
    lastName: 'Beard',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'DTP QCer',
        source: 'CO',
        target: 'JP',
      },
      {
        jobType: 'DTP',
        role: 'Webcomics translator',
        source: 'ID',
        target: 'ID',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Webcomics translator',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'AR-Z',
    userId: 70,
    email: 'nfootitt1x@phpbb.com',
    firstName: 'Brodie',
    middleName: 'Nert',
    lastName: 'Footitt',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Video editor',
        source: 'PY',
        target: 'CN',
      },
      {
        jobType: 'Misc.',
        role: 'Dubbing script translator',
        source: 'SI',
        target: 'VE',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'US-NE',
    userId: 71,
    email: 'thalversen1y@jiathis.com',
    firstName: 'Tabby',
    middleName: null,
    lastName: 'Halversen',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'Copywriter',
        source: 'ID',
        target: 'ID',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: true,
  },
  {
    id: 'US-MA',
    userId: 72,
    email: 'mpoynter1z@trellian.com',
    firstName: 'Paige',
    middleName: 'Margot',
    lastName: 'Poynter',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Webnovel translator',
        source: 'CN',
        target: 'BR',
      },
      {
        jobType: 'DTP',
        role: 'Dubbing QCer',
        source: 'SE',
        target: 'PH',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'CL-CO',
    userId: 73,
    email: 'lschiesterl20@addthis.com',
    firstName: 'Cassie',
    middleName: 'Lorri',
    lastName: 'Schiesterl',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Template QCer',
        source: 'JP',
        target: 'PK',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'US-MI',
    userId: 74,
    email: 'lcordrey21@samsung.com',
    firstName: 'Laetitia',
    middleName: 'Leonore',
    lastName: 'Cordrey',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Template QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Interpretation',
        role: 'Translator',
        source: 'PH',
        target: 'BR',
      },
      {
        jobType: 'Interpretation',
        role: 'Webcomics QCer',
        source: 'TH',
        target: 'CN',
      },
    ],
    testStatus: 'Test in progress',
    isOnboarded: false,
  },
  {
    id: 'TR-64',
    userId: 75,
    email: 'jthorby22@time.com',
    firstName: 'Emilia',
    middleName: 'Jerrine',
    lastName: 'Thorby',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'DTP QCer',
        source: 'RU',
        target: 'PL',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Template author',
        source: 'KR',
        target: 'CN',
      },
      {
        jobType: 'Misc.',
        role: 'Video editor',
        source: 'CN',
        target: 'CO',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'CA-BC',
    userId: 76,
    email: 'blambell23@oaic.gov.au',
    firstName: 'Reuben',
    middleName: 'Berni',
    lastName: 'Lambell',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'Template QCer',
        source: 'CN',
        target: 'GR',
      },
      {
        jobType: 'Documents/Text',
        role: 'DTPer',
        source: 'CZ',
        target: 'SE',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'NZ-HKB',
    userId: 77,
    email: 'nbutterly24@ebay.co.uk',
    firstName: 'Jude',
    middleName: 'Nadya',
    lastName: 'Butterly',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Editor',
        source: 'SE',
        target: 'RU',
      },
      {
        jobType: 'Webcomics',
        role: 'Subtitle QCer',
        source: 'PH',
        target: 'US',
      },
      {
        jobType: 'Documents/Text',
        role: 'Template QCer',
        source: 'BR',
        target: 'NI',
      },
      {
        jobType: 'Documents/Text',
        role: 'Editor',
        source: 'CN',
        target: 'PT',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'AE-AZ',
    userId: 78,
    email: 'sdemer25@storify.com',
    firstName: 'Eleen',
    middleName: 'Shanda',
    lastName: 'Demer',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Template author',
        source: 'AL',
        target: 'ZA',
      },
      {
        jobType: 'Documents/Text',
        role: 'SDH author',
        source: 'CN',
        target: 'PK',
      },
      {
        jobType: 'Webnovel',
        role: 'Subtitle QCer',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Interpretation',
        role: 'DTPer',
        source: 'ID',
        target: 'TN',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: true,
  },
  {
    id: 'PT-20',
    userId: 79,
    email: 'acecil26@nhs.uk',
    firstName: 'Gregory',
    middleName: 'Arabel',
    lastName: 'Cecil',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Dubbing',
        role: 'Wenovel QCer',
        source: 'ID',
        target: 'CN',
      },
      {
        jobType: 'DTP',
        role: 'DTPer',
        source: 'BR',
        target: 'PH',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: false,
  },
  {
    id: 'MY-12',
    userId: 80,
    email: 'bmollen27@eventbrite.com',
    firstName: 'Noel',
    middleName: 'Bobette',
    lastName: 'Mollen',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Webcomics translator',
        source: 'BR',
        target: 'PH',
      },
      {
        jobType: 'Misc.',
        role: 'Webnovel translator',
        source: 'NZ',
        target: 'NG',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'PG-NIK',
    userId: 81,
    email: 'bwiley28@cmu.edu',
    firstName: 'Cointon',
    middleName: 'Blanch',
    lastName: 'Wiley',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Webnovel translator',
        source: 'PH',
        target: 'SI',
      },
      {
        jobType: 'Misc.',
        role: 'QCer',
        source: 'CZ',
        target: 'ET',
      },
      {
        jobType: 'YouTube',
        role: 'QCer',
        source: 'PL',
        target: 'AR',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: true,
  },
  {
    id: 'CN-33',
    userId: 82,
    email: 'astansell29@tinypic.com',
    firstName: 'Constantine',
    middleName: 'Ardra',
    lastName: 'Stansell',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Webnovel translator',
        source: 'NG',
        target: 'KR',
      },
      {
        jobType: 'Webnovel',
        role: 'Translator',
        source: 'CN',
        target: 'CN',
      },
      {
        jobType: 'Webnovel',
        role: 'Video editor',
        source: 'RU',
        target: 'PS',
      },
      {
        jobType: 'YouTube',
        role: 'Dubbing QCer',
        source: 'CN',
        target: 'ID',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'US-WY',
    userId: 83,
    email: 'egilman2a@wunderground.com',
    firstName: 'Gottfried',
    middleName: 'Essy',
    lastName: 'Gilman',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Wenovel QCer',
        source: 'IR',
        target: 'ID',
      },
      {
        jobType: 'Dubbing',
        role: 'Audio description QCer',
        source: 'CN',
        target: 'GR',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Template QCer',
        source: 'CN',
        target: 'SY',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: true,
  },
  {
    id: 'US-MD',
    userId: 84,
    email: 'jnewns2b@goodreads.com',
    firstName: 'Selle',
    middleName: 'Janka',
    lastName: 'Newns',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'SDH author',
        source: 'SE',
        target: 'CN',
      },
      {
        jobType: 'YouTube',
        role: 'Interpreter',
        source: 'CO',
        target: 'PH',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'GB-ENG',
    userId: 85,
    email: 'gshoemark2c@howstuffworks.com',
    firstName: 'Glen',
    middleName: null,
    lastName: 'Shoemark',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Subtitle QCer',
        source: 'CU',
        target: 'CN',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: false,
  },
  {
    id: 'CN-61',
    userId: 86,
    email: 'mslixby2d@ftc.gov',
    firstName: 'Averell',
    middleName: 'Mag',
    lastName: 'Slixby',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Webnovel translator',
        source: 'UG',
        target: 'CN',
      },
      {
        jobType: 'YouTube',
        role: 'Template author',
        source: 'CN',
        target: 'FR',
      },
      {
        jobType: 'Webcomics',
        role: 'Dubbing QCer',
        source: 'LV',
        target: 'CN',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: false,
  },
  {
    id: 'US-IA',
    userId: 87,
    email: 'nmatthiesen2e@cbslocal.com',
    firstName: 'Nataline',
    middleName: null,
    lastName: 'Matthiesen',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Proofreader',
        source: 'ID',
        target: 'SV',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'PT-11',
    userId: 88,
    email: 'lsmart2f@ox.ac.uk',
    firstName: 'Manda',
    middleName: 'Lyn',
    lastName: 'Smart',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'OTT/Subtitle',
        role: 'Supp QCer',
        source: 'PH',
        target: 'US',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'DTP QCer',
        source: 'BR',
        target: 'TZ',
      },
    ],
    testStatus: 'Test submitted',
    isOnboarded: false,
  },
  {
    id: 'IE-C',
    userId: 89,
    email: 'qcutmore2g@dell.com',
    firstName: 'Valentin',
    middleName: 'Quinn',
    lastName: 'Cutmore',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'QCer',
        source: 'PK',
        target: 'CI',
      },
      {
        jobType: 'Webnovel',
        role: 'SDH author',
        source: 'BR',
        target: 'PH',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'SDH QCer',
        source: 'CN',
        target: 'US',
      },
    ],
    testStatus: 'General in progress',
    isOnboarded: true,
  },
  {
    id: 'SE-H',
    userId: 90,
    email: 'ovalance2h@nymag.com',
    firstName: 'Sandro',
    middleName: 'Orelie',
    lastName: 'Valance',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'DTP QCer',
        source: 'ID',
        target: 'CN',
      },
      {
        jobType: 'Dubbing',
        role: 'Audio description QCer',
        source: 'PT',
        target: 'BR',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: false,
  },
  {
    id: 'US-CA',
    userId: 91,
    email: 'tslimming2i@edublogs.org',
    firstName: 'Rhodie',
    middleName: 'Teddy',
    lastName: 'Slimming',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Template QCer',
        source: 'MX',
        target: 'GR',
      },
      {
        jobType: 'Dubbing',
        role: 'Editor',
        source: 'PT',
        target: 'PH',
      },
      {
        jobType: 'Webcomics',
        role: 'Translator',
        source: 'GA',
        target: 'CN',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: true,
  },
  {
    id: 'US-CA',
    userId: 92,
    email: 'ckestian2j@europa.eu',
    firstName: 'Chelsy',
    middleName: null,
    lastName: 'Kestian',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'Webcomics',
        role: 'Webcomics QCer',
        source: 'FR',
        target: 'PH',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: true,
  },
  {
    id: 'US-FL',
    userId: 93,
    email: 'rbattison2k@patch.com',
    firstName: 'Alene',
    middleName: 'Randee',
    lastName: 'Battison',
    experience: '10+ years',
    jobInfo: [
      {
        jobType: 'Webnovel',
        role: 'DTPer',
        source: 'US',
        target: 'CN',
      },
      {
        jobType: 'Documents/Text',
        role: 'Webnovel translator',
        source: 'PH',
        target: 'TH',
      },
      {
        jobType: 'Misc.',
        role: 'Supp author',
        source: 'CN',
        target: 'CN',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: true,
  },
  {
    id: 'GB-ENG',
    userId: 94,
    email: 'bcaldeiro2l@dailymail.co.uk',
    firstName: 'Celestyn',
    middleName: 'Bambi',
    lastName: 'Caldeiro',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'Interpretation',
        role: 'Supp author',
        source: 'TH',
        target: 'ID',
      },
      {
        jobType: 'YouTube',
        role: 'Subtitle author',
        source: 'CZ',
        target: 'US',
      },
    ],
    testStatus: 'Reviewing',
    isOnboarded: false,
  },
  {
    id: 'AU-QLD',
    userId: 95,
    email: 'iskillern2m@tinyurl.com',
    firstName: 'Laurette',
    middleName: 'Idalina',
    lastName: 'Skillern',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Subtitle author',
        source: 'UA',
        target: 'BD',
      },
    ],
    testStatus: 'General passed',
    isOnboarded: true,
  },
  {
    id: 'MW-MG',
    userId: 96,
    email: 'eprater2n@arizona.edu',
    firstName: 'Bret',
    middleName: 'Essy',
    lastName: 'Prater',
    experience: '1-2 year(s)',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Translator',
        source: 'FI',
        target: 'RU',
      },
      {
        jobType: 'DTP',
        role: 'Video editor',
        source: 'PH',
        target: 'KW',
      },
    ],
    testStatus: 'Review completed',
    isOnboarded: true,
  },
  {
    id: 'US-MI',
    userId: 97,
    email: 'lstone2o@sciencedaily.com',
    firstName: 'Laverna',
    middleName: null,
    lastName: 'Stone',
    experience: '3-5 years',
    jobInfo: [
      {
        jobType: 'YouTube',
        role: 'Template author',
        source: 'BR',
        target: 'ZA',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'NZ-GIS',
    userId: 98,
    email: 'odanzelman2p@surveymonkey.com',
    firstName: 'Troy',
    middleName: 'Odella',
    lastName: 'Danzelman',
    experience: 'No experience',
    jobInfo: [
      {
        jobType: 'DTP',
        role: 'Subtitle QCer',
        source: 'UA',
        target: 'BR',
      },
    ],
    testStatus: 'Test failed',
    isOnboarded: true,
  },
  {
    id: 'US-CA',
    userId: 99,
    email: 'edawe2q@digg.com',
    firstName: 'James',
    middleName: 'Eada',
    lastName: 'Dawe',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Misc.',
        role: 'Editor',
        source: 'CN',
        target: 'ID',
      },
    ],
    testStatus: 'Awaiting assignment',
    isOnboarded: false,
  },
  {
    id: 'GR-81',
    userId: 100,
    email: 'mmixer2r@imdb.com',
    firstName: 'Jordon',
    middleName: 'Madelyn',
    lastName: 'Mixer',
    experience: '6-9 years',
    jobInfo: [
      {
        jobType: 'Documents/Text',
        role: 'Proofreader',
        source: 'JP',
        target: 'RU',
      },
      {
        jobType: 'Documents/Text',
        role: 'Copywriter',
        source: 'FR',
        target: 'TZ',
      },
      {
        jobType: 'OTT/Subtitle',
        role: 'Template author',
        source: 'PT',
        target: 'RU',
      },
      {
        jobType: 'Webnovel',
        role: 'Proofreader',
        source: 'GR',
        target: 'ID',
      },
    ],
    testStatus: 'General failed',
    isOnboarded: false,
  },
]
