import axios from '@src/configs/axios'
import { JobItemType } from '@src/types/common/item.type'
import {
  AssignProFilterPostType,
  AssignProListType,
} from '@src/types/orders/job-detail'
import { makeQuery } from 'src/shared/transformer/query.transformer'

export const getAssignProList = async (
  filters: AssignProFilterPostType,
): Promise<{ totalCount: number; data: AssignProListType[] }> => {
  // const { data } = await axios.get(
  //   `/api/enough/u/pro/job?${makeQuery(filters)}`,
  // )

  const res: AssignProListType[] = [
    {
      id: '1',
      firstName: 'Kim',
      middleName: 'Minji',
      lastName: 'Leriel',
      email: 'leriel@glozinc.com',
      status: 'Onboard',
      responseRate: 20,
      assignmentStatus: 'Request accepted',
      assignmentDate: '2022-05-17T14:13:15Z',
      message: {
        id: 0,
        unReadCount: 1,
        contents: [
          {
            id: 0,
            firstName: 'Kim',
            middleName: null,
            lastName: 'Minji',
            email: 'leriel@glozinc.com',
            role: 'Pro',
            content: 'Hello',
            createdAt: '2022-05-17T14:13:15Z',
          },
        ],
      },
    },
    {
      id: '2',
      firstName: 'Kim',
      middleName: 'Minji',
      lastName: 'Leriel',
      email: 'leriel@glozinc.com',
      status: 'Onboard',
      responseRate: 30,
      assignmentStatus: 'Assigned',
      assignmentDate: '2022-05-17T14:13:15Z',
      message: {
        id: 0,
        unReadCount: 2,
        contents: null,
      },
    },
  ]

  const data = {
    totalCount: res.length,
    data: res,
  }

  return data
}

export const getJobDetails = async (id: number) => {
  const data: { corporationId: string; orderId: number; items: JobItemType[] } =
    {
      corporationId: 'O-0000017',
      orderId: 18,
      items: [
        {
          id: 1,
          itemName: 'test',
          sourceLanguage: 'en',
          targetLanguage: 'ko',
          jobs: [
            {
              id: 1,
              corporationId: 'DTP-000001',
              jobName: 'Episode 1 - Translation',
              status: 'In preparation',
              contactPerson: 'Aria Jeong',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'ko',
              startedAt: '2022-05-17T14:13:15Z',
              dueAt: '2022-05-20T14:13:15Z',
              startTimezone: {
                code: 'KR',
                label: 'Korea, Republic of',
                phone: '82',
              },
              prices: {
                id: 27,
                priceId: 24,
                sourceLanguage: 'en',
                targetLanguage: 'ko',
                priceName: 'Test',
                currency: 'KRW',
                totalPrice: 150,
                data: [
                  {
                    quantity: 1,
                    priceUnitTitle: 'CAT discount',
                    priceUnitId: 53,
                    unitPrice: 150,
                    prices: 150,
                  },
                ],
              },
              dueTimezone: {
                code: 'KR',
                label: 'Korea, Republic of',
                phone: '82',
              },
              description: 'Test',
              isShowDescription: true,
              assignedPro: {
                id: 1,
                firstName: 'Kim',
                middleName: 'Minji',
                lastName: 'Leriel',
                email: 'leriel@glozinc.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 2,
              corporationId: 'DTP-000002',
              jobName: 'Episode 2 - Localization',
              status: 'In progress',
              contactPerson: 'John Smith',
              serviceType: 'Localization',
              sourceLanguage: 'en',
              targetLanguage: 'fr',
              startedAt: '2022-06-10T09:30:00Z',
              dueAt: '2022-06-15T09:30:00Z',
              startTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              dueTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              description: 'Localization of a video game',
              isShowDescription: true,
              assignedPro: {
                id: 2,
                firstName: 'Emily',
                middleName: 'Jane',
                lastName: 'Doe',
                email: 'emily.doe@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 3,
              corporationId: 'DTP-000003',
              jobName: 'Website Translation',
              status: 'In progress',
              contactPerson: 'David Lee',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'es',
              startedAt: '2022-07-05T08:45:00Z',
              dueAt: '2022-07-10T08:45:00Z',
              startTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              dueTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              description: 'Translate website content into Spanish',
              isShowDescription: true,
              assignedPro: {
                id: 3,
                firstName: 'Maria',
                middleName: 'Isabel',
                lastName: 'Garcia',
                email: 'maria.garcia@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 4,
              corporationId: 'DTP-000004',
              jobName: 'Document Proofreading',
              status: 'In preparation',
              contactPerson: 'Alex Johnson',
              serviceType: 'Proofreading',
              sourceLanguage: 'en',
              targetLanguage: 'de',
              startedAt: '2022-08-20T13:00:00Z',
              dueAt: '2022-08-25T13:00:00Z',
              startTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              dueTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              description: 'Proofread an important legal document',
              isShowDescription: true,
              assignedPro: {
                id: 4,
                firstName: 'Julia',
                middleName: 'Müller',
                lastName: 'Schmidt',
                email: 'julia.schmidt@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 5,
              corporationId: 'DTP-000005',
              jobName: 'Subtitle Creation',
              status: 'In progress',
              contactPerson: 'Sophie Brown',
              serviceType: 'Subtitle',
              sourceLanguage: 'en',
              targetLanguage: 'ja',
              startedAt: '2022-09-10T16:30:00Z',
              dueAt: '2022-09-15T16:30:00Z',
              startTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              dueTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              description: 'Create subtitles for a movie',
              isShowDescription: true,
              assignedPro: {
                id: 5,
                firstName: 'Yuki',
                middleName: 'Sato',
                lastName: 'Tanaka',
                email: 'yuki.tanaka@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 6,
              corporationId: 'DTP-000006',
              jobName: 'Audio Transcription',
              status: 'In progress',
              contactPerson: 'Emma Wilson',
              serviceType: 'Transcription',
              sourceLanguage: 'en',
              targetLanguage: 'fr',
              startedAt: '2022-10-01T11:15:00Z',
              dueAt: '2022-10-06T11:15:00Z',
              startTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              dueTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              description: 'Transcribe audio recordings into written text',
              isShowDescription: true,
              assignedPro: {
                id: 6,
                firstName: 'Léa',
                middleName: 'Marie',
                lastName: 'Dupont',
                email: 'lea.dupont@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 7,
              corporationId: 'DTP-000007',
              jobName: 'Marketing Translation',
              status: 'In preparation',
              contactPerson: 'Daniel Chen',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'zh',
              startedAt: '2022-11-15T10:00:00Z',
              dueAt: '2022-11-20T10:00:00Z',
              startTimezone: {
                code: 'CN',
                label: 'China',
                phone: '86',
              },
              dueTimezone: {
                code: 'CN',
                label: 'China',
                phone: '86',
              },
              description: 'Translate marketing materials into Chinese',
              isShowDescription: true,
              assignedPro: {
                id: 7,
                firstName: 'Wei',
                middleName: 'Liu',
                lastName: 'Li',
                email: 'wei.li@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
            {
              id: 8,
              corporationId: 'DTP-000008',
              jobName: 'Technical Manual Translation',
              status: 'In preparation',
              contactPerson: 'Laura Davis',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'de',
              startedAt: '2023-01-05T14:30:00Z',
              dueAt: '2023-01-10T14:30:00Z',
              startTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              dueTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              description: 'Translate a technical manual into German',
              isShowDescription: true,
              assignedPro: {
                id: 8,
                firstName: 'Markus',
                middleName: 'Hoffmann',
                lastName: 'Schneider',
                email: 'markus.schneider@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
            {
              id: 9,
              corporationId: 'DTP-000009',
              jobName: 'Subtitle Editing',
              status: 'In preparation',
              contactPerson: 'Sophie Brown',
              serviceType: 'Subtitle',
              sourceLanguage: 'en',
              targetLanguage: 'it',
              startedAt: '2023-02-20T09:45:00Z',
              dueAt: '2023-02-25T09:45:00Z',
              startTimezone: {
                code: 'IT',
                label: 'Italy',
                phone: '39',
              },
              dueTimezone: {
                code: 'IT',
                label: 'Italy',
                phone: '39',
              },
              description: 'Edit subtitles for a movie',
              isShowDescription: true,
              assignedPro: {
                id: 9,
                firstName: 'Giuseppe',
                middleName: 'Ricci',
                lastName: 'Rossi',
                email: 'giuseppe.rossi@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
            {
              id: 10,
              corporationId: 'DTP-000010',
              jobName: 'Book Translation',
              status: 'In progress',
              contactPerson: 'Emily Thompson',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'fr',
              startedAt: '2023-03-10T12:00:00Z',
              dueAt: '2023-03-15T12:00:00Z',
              startTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              dueTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              description: 'Translate a novel into French',
              isShowDescription: true,
              assignedPro: {
                id: 10,
                firstName: 'Sophie',
                middleName: 'Marie',
                lastName: 'Martin',
                email: 'sophie.martin@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
          ],
        },
        {
          id: 2,
          itemName: 'Test 2',
          sourceLanguage: 'ko',
          targetLanguage: 'en',
          jobs: [
            {
              id: 11,
              corporationId: 'DTP-000011',
              jobName: 'Video Subtitling',
              status: 'In progress',
              contactPerson: 'John Smith',
              serviceType: 'Subtitle',
              sourceLanguage: 'en',
              targetLanguage: 'es',
              startedAt: '2023-04-01T16:30:00Z',
              dueAt: '2023-04-06T16:30:00Z',
              startTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              dueTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              description: 'Create subtitles for a video',
              isShowDescription: true,
              assignedPro: {
                id: 11,
                firstName: 'Maria',
                middleName: 'Rodriguez',
                lastName: 'Gonzalez',
                email: 'maria.gonzalez@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 12,
              corporationId: 'DTP-000012',
              jobName: 'Website Localization',
              status: 'In preparation',
              contactPerson: 'David Lee',
              serviceType: 'Localization',
              sourceLanguage: 'en',
              targetLanguage: 'de',
              startedAt: '2023-05-15T08:45:00Z',
              dueAt: '2023-05-20T08:45:00Z',
              startTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              dueTimezone: {
                code: 'US',
                label: 'United States',
                phone: '1',
              },
              description: 'Localize a website into German',
              isShowDescription: true,
              assignedPro: {
                id: 12,
                firstName: 'Michael',
                middleName: 'Schmidt',
                lastName: 'Müller',
                email: 'michael.muller@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 13,
              corporationId: 'DTP-000013',
              jobName: 'Document Translation',
              status: 'In progress',
              contactPerson: 'Alex Johnson',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'ja',
              startedAt: '2023-06-20T13:00:00Z',
              dueAt: '2023-06-25T13:00:00Z',
              startTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              dueTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              description: 'Translate an important document into Japanese',
              isShowDescription: true,
              assignedPro: {
                id: 13,
                firstName: 'Yuki',
                middleName: 'Suzuki',
                lastName: 'Yamamoto',
                email: 'yuki.yamamoto@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 14,
              corporationId: 'DTP-000014',
              jobName: 'Legal Document Proofreading',
              status: 'In progress',
              contactPerson: 'Emma Wilson',
              serviceType: 'Proofreading',
              sourceLanguage: 'en',
              targetLanguage: 'fr',
              startedAt: '2023-07-10T11:15:00Z',
              dueAt: '2023-07-15T11:15:00Z',
              startTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              dueTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              description: 'Proofread a legal document',
              isShowDescription: true,
              assignedPro: {
                id: 14,
                firstName: 'Lucie',
                middleName: 'Marie',
                lastName: 'Dubois',
                email: 'lucie.dubois@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
            {
              id: 15,
              corporationId: 'DTP-000015',
              jobName: 'Audio Localization',
              status: 'In progress',
              contactPerson: 'Daniel Chen',
              serviceType: 'Localization',
              sourceLanguage: 'en',
              targetLanguage: 'cn',
              startedAt: '2023-08-15T10:00:00Z',
              dueAt: '2023-08-20T10:00:00Z',
              startTimezone: {
                code: 'CN',
                label: 'China',
                phone: '86',
              },
              dueTimezone: {
                code: 'CN',
                label: 'China',
                phone: '86',
              },
              description: 'Localize audio content into Chinese',
              isShowDescription: true,
              assignedPro: {
                id: 15,
                firstName: 'Wei',
                middleName: 'Zhang',
                lastName: 'Wang',
                email: 'wei.wang@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 16,
              corporationId: 'DTP-000016',
              jobName: 'Medical Document Translation',
              status: 'In preparation',
              contactPerson: 'Laura Davis',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'es',
              startedAt: '2023-09-05T14:30:00Z',
              dueAt: '2023-09-10T14:30:00Z',
              startTimezone: {
                code: 'ES',
                label: 'Spain',
                phone: '34',
              },
              dueTimezone: {
                code: 'ES',
                label: 'Spain',
                phone: '34',
              },
              description: 'Translate a medical document into Spanish',
              isShowDescription: true,
              assignedPro: {
                id: 16,
                firstName: 'Carlos',
                middleName: 'García',
                lastName: 'Martínez',
                email: 'carlos.martinez@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 17,
              corporationId: 'DTP-000017',
              jobName: 'Software Localization',
              status: 'In progress',
              contactPerson: 'Sophie Brown',
              serviceType: 'Localization',
              sourceLanguage: 'en',
              targetLanguage: 'jp',
              startedAt: '2023-10-20T09:45:00Z',
              dueAt: '2023-10-25T09:45:00Z',
              startTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              dueTimezone: {
                code: 'JP',
                label: 'Japan',
                phone: '81',
              },
              description: 'Localize software into Japanese',
              isShowDescription: true,
              assignedPro: {
                id: 17,
                firstName: 'Hiroshi',
                middleName: 'Tanaka',
                lastName: 'Suzuki',
                email: 'hiroshi.suzuki@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 18,
              corporationId: 'DTP-000018',
              jobName: 'Transcription',
              status: 'In progress',
              contactPerson: 'Emily Thompson',
              serviceType: 'Transcription',
              sourceLanguage: 'en',
              targetLanguage: 'ko',
              startedAt: '2023-11-10T12:00:00Z',
              dueAt: '2023-11-15T12:00:00Z',
              startTimezone: {
                code: 'KR',
                label: 'Korea, Republic of',
                phone: '82',
              },
              dueTimezone: {
                code: 'KR',
                label: 'Korea, Republic of',
                phone: '82',
              },
              description: 'Transcribe audio recordings',
              isShowDescription: true,
              assignedPro: {
                id: 18,
                firstName: 'Seojin',
                middleName: 'Kim',
                lastName: 'Lee',
                email: 'seojin.lee@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 19,
              corporationId: 'DTP-000019',
              jobName: 'Marketing Content Localization',
              status: 'In progress',
              contactPerson: 'David Lee',
              serviceType: 'Localization',
              sourceLanguage: 'en',
              targetLanguage: 'fr',
              startedAt: '2023-12-15T08:45:00Z',
              dueAt: '2023-12-20T08:45:00Z',
              startTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              dueTimezone: {
                code: 'FR',
                label: 'France',
                phone: '33',
              },
              description: 'Localize marketing content into French',
              isShowDescription: true,
              assignedPro: {
                id: 19,
                firstName: 'Julie',
                middleName: 'Marie',
                lastName: 'Dupont',
                email: 'julie.dupont@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },

            {
              id: 20,
              corporationId: 'DTP-000020',
              jobName: 'Technical Document Translation',
              status: 'In preparation',
              contactPerson: 'Alex Johnson',
              serviceType: 'Translation',
              sourceLanguage: 'en',
              targetLanguage: 'de',
              startedAt: '2024-01-05T14:30:00Z',
              dueAt: '2024-01-10T14:30:00Z',
              startTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              dueTimezone: {
                code: 'DE',
                label: 'Germany',
                phone: '49',
              },
              description: 'Translate a technical document into German',
              isShowDescription: true,
              assignedPro: {
                id: 20,
                firstName: 'Markus',
                middleName: 'Schneider',
                lastName: 'Müller',
                email: 'markus.muller@example.com',
                isActive: true,
                isOnboarded: true,
              },
              files: [
                {
                  name: 'test-file',
                  size: 100000,
                  file: 'https://gloground.com',
                  type: 'SAMPLE',
                },
                {
                  name: 'test-file2',
                  size: 100500,
                  file: 'https://gloground.com',
                  type: 'TARGET',
                },
              ],
            },
          ],
        },
      ],
    }
  return data
}
