export const TADHeader1 = [
  'Onboarding overview',
  '',
  '',
  'Language Pool',
  '',
  '',
  '',
  'Job type/Role',
  '',
  '',
  '',
  '',
  'Application Status',
  'Application Number',
  'Applied job types',
  'Applied job types Number',
  'Applied job types Percent',
  'Applied roles',
  'Applied roles Number',
  'Applied roles Percent',
  'Applied source languages',
  'Applied source languages Number',
  'Applied source languages Percent',
]

export const TADHeader2 = [
  'Onboarded Pros',
  'Onboarding in progress',
  'Failed Pros',
  'Source languages',
  'Target languages',
  'Number',
  'Percent',
  'Job Type',
  'Role',
  'Number',
  'Percent',
  '',
  '',
  '',
  '',
  '',
]
