export const JobTypeColor = {
  'Documents/Text': '#ff9E90',
  Dubbing: '#fff387',
  Interpretation: '#CBFFEC',
  'Misc.': '#BFF0FF',
  'OTT/Subtitle': '#A9E0FF',
  Webcomics: '#BEEFAE',
  Webnovel: '#FFBFE9',
} as const

export const RoleColor = {
  DTPer: '#FF985E',
  'DTP QCer': '#BC9459',
  QCer: '#6638A1',
  Transcriber: '#921010',
  Translator: '#9024C3',
  'Audio describer': '#E0CA00',
  'Audio description QCer': '#D1C76B',
  'Dubbing audio QCer': '#A89F52',
  'Dubbing script QCer': '#A98A1B',
  'Dubbing script translator': '#6F6934',
  'Dubbing voice artist': '#37330F',
  Interpreter: '#80FCCF',
  Copywriter: '#BFF0FF',
  Editor: '#67DBFF',
  'Video editor': '#CFDBDE',
  'SDH author': '#8EB7DC',
  'SDH QCer': '#2D83D2',
  'Subtitle author': '#3A5ACE',
  'Subtitle QCer': '#213478',
  'Supp author': '#1351EF',
  'Supp QCer': '#085886',
  'Template author': '#1ACEF5',
  'Template QCer': '#15A0BE',
  Proofreader: '#66D841',
  'Webcomics QCer': '#6DAA59',
  'Webcomics translator': '#357D1D',
  'Webnovel QCer': '#F569C5',
  'Webnovel translator': '#CD4BA0',
} as const

export const TestStatusColor = {
  'Awaiting assignment': '#6D788D',
  'Test assigned': '#8232C0',
  'Basic in progress': '#FDB528',
  'Basic submitted': '#1A6BBA',
  'Basic failed': '#FF4D49',
  'Basic passed': '#72E128',
  'Skill in progress': '#D18A00',
  'Skill submitted': '#1A6BBA',
  Reviewing: '#21AEDB',
  'Review completed': '#2B6603',
  'Skill failed': '#FF4D49',
  Paused: '#6D788D',
  Rejected: '#FF4D49',
}

export const TestTypeColor = {
  'Basic test': '#FDB528',
  'Skill test': '#666CFF',
}
