export const JobTypeColor = {
  'Documents/Text': '#ff9E90',
  DTP: '#FFC875',
  Dubbing: '#fff387',
  Interpretation: '#87FFD4',
  'Misc.': '#BFF0FF',
  'OTT/Subtitle': '#A9E0FF',
  Webcomics: '#BEEFAE',
  Webnovel: '#FFBFE9',
  YouTube: '#CCBFFF',
} as const

export const RoleColor = {
  QCer: '#FF9E90',
  Translator: '#D33DA0',
  'DTP QCer': '#BC9459',
  DTPer: '#FFBE5E',
  'Audio description QCer': '#D1C76B',
  'Dubbing QCer': '#A89F52',
  'Dubbing script translator': '#6F6934',
  Interpreter: '#CBFFEC',
  Copywriter: '#BFF0FF',
  Editor: '#67DBFF',
  'Video editor': '#CFDBDE',
  'SDH author': '#8EB7DC',
  'SDH QCer': '#2D83D2',
  'Subtitle author': '#3A5ACE',
  'Subtitle QCer': '#213478',
  'Template author': '#1ACEF5',
  'Template QCer': '#15A0BE',
  'Supp author': '#1351EF',
  'Supp QCer': '#085886',
  Proofreader: '#66D841',
  'Webcomics QCer': '#6DAA59',
  'Webcomics translator': '#36562B',
  'Webnovel translator': '#CD4BA0',
  'Webnovel QCer': '#F569C5',
}

export const TestStatusColor = {
  'Awaiting assignment': '#6D788D',
  'Test assigned': '#8232C0',
  'General in progress': '#FDB528',
  'General failed': '#FF4D49',
  'General passed': '#64C623',
  'Test in progress': '#D18A00',
  'Test submitted': '#1A6BBA',
  Reviewing: '#21AEDB',
  'Review completed': '#2B6603',
  'Test failed': '#FF4D49',
  default: '#6D788D',
}
