export const FormErrors = {
  invalidEmail: 'Invalid email address',
  invalidUrl: 'Invalid link',
  notHTTPPrefixUrl: 'Please include http:// or https:// in the website address',
  registeredEmail: 'This email is already registered',
  invalidVerificationCode: 'Invalid verification code',
  required: 'This field is required',
  fileSizeExceed: 'The file size is too large',
  loginFailed: 'Your email or password was entered incorrectly',
  alreadyRegistered: 'This account is already registered',
  checkbox: 'Field must be checked',
  passwordLength: '9-20 characters',
  passwordRegexCase: 'Uppercase and lowercase characters',
  passwordDoesntMatch: 'Password doesn’t match',
  passwordRegexSpecialChar: 'At least one number and special character',
  invalidNumber: 'Invalid number',
  invalidCardNumber: 'Only numbers and special characters are allowed',
  invalidZipCode: 'Zip code contains invalid characters: (){}[]~\\;:"\'!?&#*+=…`^_|/',
} as const
