import { InvoiceMultipleOrderType } from '@src/types/invoice/common.type'
import axios from 'src/configs/axios'
import { makeQuery } from 'src/shared/transformer/query.transformer'

export const getInvoiceStatusList = async (): Promise<
  Array<{ id: number; statusName: string }>
> => {
  try {
    const { data } = await axios.get(
      `/api/enough/u/invoice-receivable/status/list`,
    )
    return data.data
  } catch (e: any) {
    return []
  }
}

export const getInvoicePayableStatusList = async (): Promise<
  Array<{ id: number; statusName: string }>
> => {
  try {
    const { data } = await axios.get(
      `/api/enough/u/invoice/payable/status/list`,
    )
    return data.data
  } catch (e: any) {
    return []
  }
}

export const getMultipleOrder = async (
  id: number[],
): Promise<InvoiceMultipleOrderType> => {
  const { data } = await axios.get(
    `/api/enough/u/order/target-items?${makeQuery({ order: id })}`,
  )

  // const data: InvoiceMultipleOrderType = {
  //   clientInfo: {
  //     addressType: 'billing',
  //     client: {
  //       clientId: 7,
  //       // corporationId: 'C-000007',
  //       // authorId: 5,
  //       // adminCompanyName: 'GloZ',
  //       // clientType: 'Company',
  //       name: 'Naver1',
  //       email: 'aaa@naver.com',
  //       phone: '1111111',
  //       mobile: '01011112222',
  //       fax: '01011112222222222333',
  //       // websiteLink: 'https://naver.com',
  //       // status: 'New',
  //       timezone: {
  //         code: 'KR',
  //         label: 'Korea, Republic of',
  //         phone: '82',
  //       },
  //       // isReferred: true,
  //       // companyId: 'd12ceacb-bc1c-4006-8a74-20fb66eae68c',
  //       // createdAt: '2023-08-06T22:10:21.934Z',
  //       // updatedAt: '2023-10-16T21:15:32.127Z',
  //       // deletedAt: null,
  //       taxable: false,
  //       tax: Number('30'),
  //     },
  //     isEnrolledClient: true,
  //     clientAddress: [
  //       {
  //         id: '11',
  //         createdAt: '2023-04-19T05:05:29.473Z',
  //         updatedAt: '2023-04-19T05:05:29.473Z',
  //         addressType: 'billing',
  //         name: null,
  //         baseAddress: null,
  //         detailAddress: null,
  //         city: null,
  //         state: null,
  //         country: null,
  //         zipCode: null,
  //         isSelected: false,
  //       },
  //       {
  //         id: '12',
  //         createdAt: '2023-04-19T05:05:29.473Z',
  //         updatedAt: '2023-04-19T05:05:29.473Z',
  //         addressType: 'shipping',
  //         name: null,
  //         baseAddress: null,
  //         detailAddress: null,
  //         city: null,
  //         state: null,
  //         country: null,
  //         zipCode: null,
  //         isSelected: true,
  //       },
  //     ],
  //   },
  //   revenueFrom: 'Korea',
  //   orders: [
  //     {
  //       id: 179,
  //       projectName: 'Test project',
  //       corporationId: 'O-000001',
  //       languagePairs: [
  //         {
  //           id: 430,

  //           source: 'ko',
  //           target: 'en',
  //           price: null,
  //           minimumPrice: '5.00000',
  //           currency: 'USD',
  //         },
  //         {
  //           id: 431,

  //           source: 'ko',
  //           target: 'ja',
  //           price: null,
  //           minimumPrice: '100.00000',
  //           currency: 'USD',
  //         },
  //       ],
  //       items: [
  //         {
  //           contactPerson: {
  //             userId: 5,
  //             email: 'd_master_1@glozinc.com',
  //             firstName: 'Masterr',
  //             lastName: 'K',
  //             middleName: 'D',
  //             timezone: { code: 'AD', label: 'Andorra', phone: '376' },
  //           },
  //           description: '',
  //           dueAt: '2023-11-29T15:00:00.000Z',
  //           id: 243,
  //           itemName: 'Item 1',
  //           source: 'ko',
  //           target: 'en',
  //           priceId: 65,
  //           showItemDescription: false,
  //           minimumPriceApplied: false,
  //           totalPrice: Number('293161.50000'),
  //           priceFactor: 0,
  //           initialPrice: {
  //             id: 130,
  //             createdAt: '2023-10-30T02:37:51.310Z',
  //             updatedAt: '2023-10-30T02:37:51.310Z',
  //             name: '[Hope] price unit edit',
  //             priceId: 65,
  //             isStandard: true,
  //             category: 'Documents/Text',
  //             serviceType: ['DTP', 'DTP QC', 'DTP file prep'],
  //             currency: 'USD',
  //             calculationBasis: 'Characters',
  //             rounding: 3,
  //             numberPlace: 2,
  //             authorId: 5,
  //             memo: null,
  //             deletedAt: null,
  //             priceUnits: [
  //               {
  //                 id: 217,
  //                 createdAt: '2023-10-30T02:37:51.310Z',
  //                 updatedAt: '2023-10-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '50.00000',
  //                 isBase: false,
  //                 quantity: 195441,
  //                 price: Number('1.50000'),
  //                 authorId: 5,
  //                 parentPriceUnitId: 142,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             ],
  //           },
  //           minimumPrice: Number('5.00000'),
  //           detail: [
  //             {
  //               id: 514,

  //               quantity: 195441,
  //               priceUnitId: 176,
  //               unitPrice: Number('1.50000'),
  //               prices: '293161.50000',
  //               unit: 'Characters',
  //               currency: 'USD',
  //               initialPriceUnit: {
  //                 id: 217,
  //                 createdAt: '2023-10-30T02:37:51.310Z',
  //                 updatedAt: '2023-10-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '50.00000',
  //                 isBase: false,
  //                 quantity: 195441,
  //                 price: Number('1.50000'),
  //                 authorId: 5,
  //                 parentPriceUnitId: 142,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       id: 180,
  //       projectName: 'Test project 2',
  //       corporationId: 'O-000002',
  //       languagePairs: [
  //         {
  //           id: 432,
  //           source: 'en',
  //           target: 'ko',
  //           price: null,
  //           minimumPrice: '10.00000',
  //           currency: 'USD',
  //         },
  //         {
  //           id: 433,
  //           source: 'en',
  //           target: 'ja',
  //           price: null,
  //           minimumPrice: '200.00000',
  //           currency: 'USD',
  //         },
  //       ],
  //       items: [
  //         {
  //           contactPerson: {
  //             userId: 6,
  //             email: 'e_master_1@glozinc.com',
  //             firstName: 'Master',
  //             lastName: 'E',
  //             middleName: 'F',
  //             timezone: {
  //               code: 'AE',
  //               label: 'United Arab Emirates',
  //               phone: '971',
  //             },
  //           },
  //           description: '',
  //           dueAt: '2023-12-29T15:00:00.000Z',
  //           id: 244,
  //           itemName: 'Item 2',
  //           source: 'en',
  //           target: 'ko',
  //           priceId: 66,
  //           showItemDescription: false,
  //           minimumPriceApplied: false,
  //           totalPrice: Number('400000.00000'),
  //           priceFactor: 0,
  //           initialPrice: {
  //             id: 131,
  //             createdAt: '2023-11-30T02:37:51.310Z',
  //             updatedAt: '2023-11-30T02:37:51.310Z',
  //             name: '[Hope] price unit edit',
  //             priceId: 66,
  //             isStandard: true,
  //             category: 'Documents/Text',
  //             serviceType: ['DTP', 'DTP QC', 'DTP file prep'],
  //             currency: 'USD',
  //             calculationBasis: 'Characters',
  //             rounding: 3,
  //             numberPlace: 2,
  //             authorId: 6,
  //             memo: null,
  //             deletedAt: null,
  //             priceUnits: [
  //               {
  //                 id: 218,
  //                 createdAt: '2023-11-30T02:37:51.310Z',
  //                 updatedAt: '2023-11-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '60.00000',
  //                 isBase: false,
  //                 quantity: 200000,
  //                 price: Number('2.00000'),
  //                 authorId: 6,
  //                 parentPriceUnitId: 143,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             ],
  //           },
  //           minimumPrice: Number('10.00000'),
  //           detail: [
  //             {
  //               id: 515,
  //               quantity: 200000,
  //               priceUnitId: 177,
  //               unitPrice: Number('2.00000'),
  //               prices: '400000.00000',
  //               unit: 'Characters',
  //               currency: 'USD',
  //               initialPriceUnit: {
  //                 id: 218,
  //                 createdAt: '2023-11-30T02:37:51.310Z',
  //                 updatedAt: '2023-11-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '60.00000',
  //                 isBase: false,
  //                 quantity: 200000,
  //                 price: Number('2.00000'),
  //                 authorId: 6,
  //                 parentPriceUnitId: 143,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       id: 181,
  //       projectName: 'Test projet 3',
  //       corporationId: 'O-000003',
  //       languagePairs: [
  //         {
  //           id: 434,
  //           source: 'ja',
  //           target: 'ko',
  //           price: null,
  //           minimumPrice: '15.00000',
  //           currency: 'USD',
  //         },
  //         {
  //           id: 435,
  //           source: 'ja',
  //           target: 'en',
  //           price: null,
  //           minimumPrice: '300.00000',
  //           currency: 'USD',
  //         },
  //       ],
  //       items: [
  //         {
  //           contactPerson: {
  //             userId: 7,
  //             email: 'g_master_1@glozinc.com',
  //             firstName: 'Master',
  //             lastName: 'G',
  //             middleName: 'H',
  //             timezone: { code: 'AF', label: 'Afghanistan', phone: '93' },
  //           },
  //           description: '',
  //           dueAt: '2024-01-29T15:00:00.000Z',
  //           id: 245,
  //           itemName: 'Item 3',
  //           source: 'ja',
  //           target: 'ko',
  //           priceId: 67,
  //           showItemDescription: false,
  //           minimumPriceApplied: false,
  //           totalPrice: Number('500000.00000'),
  //           priceFactor: 0,
  //           initialPrice: {
  //             id: 132,
  //             createdAt: '2023-12-30T02:37:51.310Z',
  //             updatedAt: '2023-12-30T02:37:51.310Z',
  //             name: '[Hope] price unit edit',
  //             priceId: 67,
  //             isStandard: true,
  //             category: 'Documents/Text',
  //             serviceType: ['DTP', 'DTP QC', 'DTP file prep'],
  //             currency: 'USD',
  //             calculationBasis: 'Characters',
  //             rounding: 3,
  //             numberPlace: 2,
  //             authorId: 7,
  //             memo: null,
  //             deletedAt: null,
  //             priceUnits: [
  //               {
  //                 id: 219,
  //                 createdAt: '2023-12-30T02:37:51.310Z',
  //                 updatedAt: '2023-12-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '70.00000',
  //                 isBase: false,
  //                 quantity: 250000,
  //                 price: Number('2.00000'),
  //                 authorId: 7,
  //                 parentPriceUnitId: 144,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             ],
  //           },
  //           minimumPrice: Number('15.00000'),
  //           detail: [
  //             {
  //               id: 516,
  //               quantity: 250000,
  //               priceUnitId: 178,
  //               unitPrice: Number('2.00000'),
  //               prices: '500000.00000',
  //               unit: 'Characters',
  //               currency: 'USD',
  //               initialPriceUnit: {
  //                 id: 219,
  //                 createdAt: '2023-12-30T02:37:51.310Z',
  //                 updatedAt: '2023-12-30T02:37:51.310Z',
  //                 title: 'No Match',
  //                 unit: 'Characters',
  //                 weighting: '70.00000',
  //                 isBase: false,
  //                 quantity: 250000,
  //                 price: Number('2.00000'),
  //                 authorId: 7,
  //                 parentPriceUnitId: 144,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             },
  //           ],
  //         },
  //         {
  //           id: 242,
  //           priceFactor: 1000,
  //           itemName: 'Item 2 - japa',
  //           dueAt: '2023-11-07T06:00:00.000Z',
  //           sourceLanguage: 'ko',
  //           targetLanguage: 'ja',
  //           priceId: 63,
  //           description: '',
  //           showItemDescription: false,
  //           minimumPriceApplied: false,
  //           totalPrice: Number('3593.52000'),

  //           initialPrice: {
  //             id: 129,
  //             createdAt: '2023-10-29T17:36:08.788Z',
  //             updatedAt: '2023-10-29T17:36:08.788Z',
  //             name: 'QA 0920',
  //             priceId: 63,
  //             isStandard: true,
  //             category: 'OTT/Subtitle',
  //             serviceType: ['Translation', 'Transcription', 'Subtitle'],
  //             currency: 'USD',
  //             calculationBasis: 'Words',
  //             rounding: 0,
  //             numberPlace: 2,
  //             authorId: 7687,
  //             memo: 'QA Test',
  //             deletedAt: null,
  //             priceUnits: [
  //               {
  //                 id: 216,
  //                 createdAt: '2023-10-29T17:36:08.788Z',
  //                 updatedAt: '2023-10-29T17:36:08.788Z',
  //                 title: 'QA 0920 자식2',
  //                 unit: 'Words',
  //                 weighting: '92.00000',
  //                 isBase: false,
  //                 quantity: 1953,
  //                 price: Number('1.84000'),
  //                 authorId: 7687,
  //                 parentPriceUnitId: 136,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             ],
  //           },
  //           minimumPrice: Number('100.00000'),
  //           contactPerson: {
  //             userId: 5,
  //             firstName: 'Masterr',
  //             middleName: 'D',
  //             lastName: 'K',
  //             email: 'd_master_1@glozinc.com',
  //             timezone: null,
  //           },
  //           detail: [
  //             {
  //               id: 513,

  //               quantity: 1953,
  //               priceUnitId: 138,
  //               unitPrice: Number('1.84000'),
  //               prices: '3593.52000',
  //               unit: 'Words',
  //               currency: 'USD',
  //               initialPriceUnit: {
  //                 id: 216,
  //                 createdAt: '2023-10-29T17:36:08.788Z',
  //                 updatedAt: '2023-10-29T17:36:08.788Z',
  //                 title: 'QA 0920 자식2',
  //                 unit: 'Words',
  //                 weighting: '92.00000',
  //                 isBase: false,
  //                 quantity: 1953,
  //                 price: Number('1.84000'),
  //                 authorId: 7687,
  //                 parentPriceUnitId: 136,
  //                 isActive: true,
  //                 deletedAt: null,
  //                 unitPrice: 0,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // }

  // return data
  return data
}
